### ISSUE TITLE
Setup SSHD configuration in coordinator server

### ISSUE THREAD

**Issue by elventear** [radiasoft/ansible-conf#44]
Ensure all required configuration is available before provisioning slave hosts. Store all the information in an NFS share. 

Required by #38.

**Comment by elventear** [comment]
Not using NFS for SSHD.

**Comment by bruhwiler** [comment]
Please don't use 'slave' for RadiaSoft software or projects.

Instead of the master/slave analogy, please use one of the following
alternatives, whichever offers the best analogy to the business logic being
implemented:
  primary/secondary
  primary/replica
  parent/child
  manager/worker
  coordinator/worker

**Comment by elventear** [comment]
Ok.
